import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

// mantine
import '@mantine/core/styles.css';

import { MantineProvider } from '@mantine/core';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'John Doe',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>

        <MantineProvider defaultColorScheme='auto'>
          <div className='animate-fade-in'>
             {children}
            
          </div>
         
          

          
        </MantineProvider>
        
        </body>
    </html>
  )
}
